NotarNotarBundle_login:
    pattern:  /admin
    defaults: { _controller: NotarNotarBundle:Login:login }
    
NotarNotarBunde_admin_homepage:
    pattern:  /admin/home
    defaults: { _controller: NotarNotarBundle:Admin:index }


NotarNotarBunde_admin_users:
    pattern:  /admin/users
    defaults: { _controller: NotarNotarBundle:Admin:users }


