FrontFrontBundle:
    resource: "@FrontFrontBundle/Resources/config/routing.yml"
    prefix:   /

DocDocBundle:
    resource: "@DocDocBundle/Resources/config/routing.yml"
    prefix:   /

NotarNotarBundle:
    resource: "@NotarNotarBundle/Resources/config/routing.yml"
    prefix:   /

UserUserBundle:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
