FrontFrontBundle_homepage:
    pattern:  /
    defaults: { _controller: FrontFrontBundle:Doc:homepage }
    
FrontFrontBundle_cum_lucreaza:
    pattern:  /how-it-works
    defaults: { _controller: FrontFrontBundle:Doc:howItWorks }
    
FrontFrontBundle_step1:
    pattern:  /step1
    defaults: { _controller: FrontFrontBundle:Doc:step1 }
    
FrontFrontBundle_step2:
    pattern:  /step2
    defaults: { _controller: FrontFrontBundle:Doc:step2 }
    
FrontFrontBundle_step3:
    pattern:  /step3
    defaults: { _controller: FrontFrontBundle:Doc:step3 }
    
FrontFrontBundle_step4:
    pattern:  /step4
    defaults: { _controller: FrontFrontBundle:Doc:step4 }
    
FrontFrontBundle_step5:
    pattern:  /step5
    defaults: { _controller: FrontFrontBundle:Doc:step5 }
    
FrontFrontBundle_login_register:
    pattern:  /login-register
    defaults: { _controller: FrontFrontBundle:Doc:loginRegister }
    
ajax:
  pattern: /ajax
  defaults: { _controller: FrontFrontBundle:Ajax:ajax }
    
ajax_notar:
  pattern: /ajax_notar
  defaults: { _controller: FrontFrontBundle:Ajax:ajaxNotar }
  
FrontFrontBundle_register:
    pattern:  /register
    defaults: { _controller: FrontFrontBundle:Doc:Register }

FrontFrontBundle_login:
    pattern:  /login
    defaults: { _controller: FrontFrontBundle:Doc:login }

FrontFrontBundle_my_orders:
    pattern:  /my-orders
    defaults: { _controller: FrontFrontBundle:Doc:MyOrders }
    
